name: Run Mohit Bot

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/30 * * * *'  # Every 30 minutes
  workflow_dispatch:        # Manual trigger option

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install -r H_Requirements.txt

      - name: Run Bot
        env:
          FB_EMAIL: ${{ secrets.FB_EMAIL }}
          FB_PASSWORD: ${{ secrets.FB_PASSWORD }}
          FB_COOKIES: ${{ secrets.FB_COOKIES }}
          LOGIN_METHOD: cookies  # Use 'cookies' or 'email' (manual login is not interactive in Actions)
        run: python G_Main.py

